# Generated by Django 3.1.4 on 2021-01-08 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('volume', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Volume, m3')),
                ('cement_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Cement, kg')),
                ('sand_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Sand, kg')),
                ('gravel_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Gravel, kg')),
                ('water_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Water, kg')),
                ('admixture_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Admixture, kg')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.recipe', verbose_name='Recipe')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
